spring:
  datasource:
    url: jdbc:h2:mem:cash_gl;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  sql:
    init:
      mode: always
  main:
    web-application-type: none
logging:
  level:
    com.universal.reconciliation.ingestion: INFO
