spring:
  datasource:
    url: jdbc:h2:mem:recon;MODE=MYSQL;DATABASE_TO_UPPER=false
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
    defer-datasource-initialization: true
  ldap:
    embedded:
      base-dn: dc=universal,dc=local
      credential:
        username: uid=admin
        password: admin
      ldif: classpath:ldap-data.ldif
      port: 0
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always

app:
  security:
    jwt:
      secret: dW5pdmVyc2FsLXJlY29uLXNlY3JldC1zaWduaW5nLWtleQ==
      expiration-seconds: 86400
    ldap:
      people-base: ou=people,dc=universal,dc=local
      groups-base: ou=groups,dc=universal,dc=local

logging:
  level:
    root: INFO
    com.universal.reconciliation: DEBUG
