spring:
  datasource:
    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:recon}?createDatabaseIfNotExist=true
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USER:recon}
    password: ${DB_PASSWORD:recon}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  sql:
    init:
      mode: always
      platform: mariadb
