spring:
  datasource:
    url: jdbc:h2:mem:recon;MODE=MYSQL;DATABASE_TO_UPPER=false
    driver-class-name: org.h2.Driver
    username: sa
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
    defer-datasource-initialization: true
  ldap:
    embedded:
      base-dn: dc=universal,dc=local
      credential:
        username: uid=admin
        password: ${LDAP_ADMIN_PASSWORD:}
      ldif: classpath:ldap-data.ldif
      port: 0
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always

app:
  security:
    jwt:
      secret: ${JWT_SECRET:bG9jYWwtZGV2LWp3dC1zZWNyZXQta2V5LTMyYnl0ZXMhIQ==}
      expiration-seconds: 86400
    ldap:
      people-base: ${LDAP_PEOPLE_BASE:ou=people,dc=universal,dc=local}
      groups-base: ${LDAP_GROUPS_BASE:ou=groups,dc=universal,dc=local}
      user-dn-pattern: ${LDAP_USER_DN_PATTERN:uid={0},ou=people}
    cors:
      allowed-origins:
        - ${APP_ALLOWED_ORIGINS:http://localhost:4200}

logging:
  level:
    root: INFO
    com.universal.reconciliation: DEBUG
